apiVersion: v1
kind: Service
metadata:
  name: pos-app-service
spec:
  selector:
    app: pos-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000 # Access the app on Minikube IP:30000
  type: NodePort
