name: admin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  hexcolor: ^3.0.1
  fluentui_system_icons: ^1.1.273
  flutter_svg: ^2.2.0
  dio: ^5.7.0
  get_storage: ^2.1.1
  json_annotation: ^4.9.0
  file_picker: ^10.2.0
  printing: ^5.14.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  qr_code_scanner_plus: ^2.0.12
  firebase_core: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.5.1

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/jpg/
